fix: netlify prisma module not found
error: Module not found: Can't resolve
'@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs'

maybe the issue is because not all prisma-related libs are version
matched?